Typify message exchange between extension scripts
- Reduce the number of "any" types in domain logic.
- Stop using the "runtime.connect()" API from the content script. We're
  used to utilizing it to associate messages from the content script
  with a tab ID, but it turned out that:
  1. Opening ports from a content script in Chrome
     ("chrome.runtime.connect") inevitably leads to the error "Unchecked
     runtime.lastError: The page keeping the extension port is moved
     into back/forward cache, so the message channel is closed" — during
     ordinary navigation by links.
  2. The "onMessage" handler in the background service worker
     successfully receives the tab ID for messages sent from the content
     script without using a special port (via "runtime.sendMessage").